### ISSUE TITLE
0.18.0.0 seems to cause misaligned sections

### ISSUE THREAD

**Issue by mathstuf** [mayeut/patchelf-pypi#87]
Our CI started failing today using the `manylinux2014` image. Given the symptom and the `dist-info` diff of a single installation (A/D seems to be backwards from what I'd expect):

```
% podman diff 879520bd4b55f4db71fb325219fe390c487f3d5409c4f89ea4201bbc1d18dd5b 4901c60f84c46a321c15d5283ed541efcbcf8c566bfc0cb52171af4cfa800d11 | grep dist-info$ | grep 3.10
C /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/tomli-2.0.1.dist-info
C /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/pyproject_hooks-1.0.0.dist-info
C /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/build-0.10.0.dist-info
C /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/packaging-23.1.dist-info
A /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/pip-23.1.dist-info
C /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/wheel-0.40.0.dist-info
A /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/setuptools-67.6.1.dist-info
D /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/setuptools-67.7.1.dist-info
D /opt/_internal/cpython-3.10.11/lib/python3.10/site-packages/pip-23.1.1.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/build-0.10.0.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/pyproject_hooks-1.0.0.dist-info
A /opt/_internal/tools/lib/python3.10/site-packages/setuptools-67.6.1.dist-info
A /opt/_internal/tools/lib/python3.10/site-packages/pip-23.1.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/pipx-1.2.0.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/userpath-1.8.0.dist-info
A /opt/_internal/tools/lib/python3.10/site-packages/argcomplete-3.0.5.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/certifi-2022.12.7.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/click-8.1.3.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/packaging-23.1.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/tomli-2.0.1.dist-info
C /opt/_internal/tools/lib/python3.10/site-packages/wheel-0.40.0.dist-info
D /opt/_internal/tools/lib/python3.10/site-packages/pip-23.1.1.dist-info
D /opt/_internal/tools/lib/python3.10/site-packages/argcomplete-3.0.8.dist-info
D /opt/_internal/tools/lib/python3.10/site-packages/setuptools-67.7.1.dist-info
A /opt/_internal/pipx/shared/lib/python3.10/site-packages/pip-23.1.dist-info
A /opt/_internal/pipx/shared/lib/python3.10/site-packages/setuptools-67.6.1.dist-info
C /opt/_internal/pipx/shared/lib/python3.10/site-packages/wheel-0.40.0.dist-info
D /opt/_internal/pipx/shared/lib/python3.10/site-packages/setuptools-67.7.2.dist-info
D /opt/_internal/pipx/shared/lib/python3.10/site-packages/pip-23.1.1.dist-info
C /opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel-5.3.0.dist-info
C /opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/pyelftools-0.29.dist-info
C /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake-3.26.3.dist-info
A /opt/_internal/pipx/venvs/patchelf/lib/python3.10/site-packages/patchelf-0.17.2.1.dist-info
D /opt/_internal/pipx/venvs/patchelf/lib/python3.10/site-packages/patchelf-0.18.0.0.dist-info
C /opt/_internal/pipx/venvs/swig/lib/python3.10/site-packages/swig-4.1.1.dist-info
```

between these two containers:

```
Working: quay.io/pypa/manylinux2014_x86_64@sha256:bc1b92cee27af8cd949e6abb7036ec17e2ce66066a89131fdf6ec9212c6762e3
Broken : quay.io/pypa/manylinux2014_x86_64@sha256:d2e6fbda70ff201243e824a86b5ce3dc3f93fa56865d1d84a2a3ac0578c86826
```

our generated wheels now have the following error when trying to import our modules:

```
$ venv/bin/python -c "import vtk"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builds/gitlab-kitware-sciviz-ci/venv/lib/python3.10/site-packages/vtk.py", line 5, in <module>
    from vtkmodules.vtkWebCore import *
ImportError: libXcursor-1a09904e.so.1.0.2: ELF load command address/offset not properly aligned
```

Something seems to have broken this between 0.17.2.1 and 0.18.0.0.

**Comment by SeanCurtis-TRI** [comment]
Looks like they're reverting.

**Comment by satmandu** [comment]
Any chance of deleting the 18.0.0 tag here and also on pypi so it doesn't show up as the [latest release](https://pypi.org/project/patchelf/0.18.0.0/) for patchelf on pypi?

**Comment by nv-kmcgill53** [comment]
Any updates on this? 0.18.0 is the current version defined in the `apt` repository for the [LTS Ubuntu 24.04 version](https://packages.ubuntu.com/search?keywords=patchelf&searchon=names&suite=oracular&section=all). Can this be updated to point at 0.17.2?

**Comment by mayeut** [comment]
> Any updates on this? 0.18.0 is the current version defined in the apt repository for the [LTS Ubuntu 24.04 version](https://packages.ubuntu.com/search?keywords=patchelf&searchon=names&suite=oracular&section=all). Can this be updated to point at 0.17.2?

This repo just packages the upstream https://github.com/NixOS/patchelf for [PyPI](https://pypi.org/project/patchelf/) to allow pip/pipx/uv install.
This repo has nothing to do with what is being packaged in Ubuntu.

The 0.18.0 version is already yanked in [PyPI](https://pypi.org/project/patchelf/0.18.0.0/).
We're waiting for a fix/new version upstream (https://github.com/NixOS/patchelf/issues/492) to publish a new version.
There's nothing to do here for now.

**Comment by mayeut** [comment]
0.19.1.0 should fix this
